#!/bin/sh
if [ -f ./.env ] ; then
    export $(cat .env | grep -v ^# | xargs);
fi
if [ ! $GRMS_BACKUPDIR ]; then
    echo "env GRMS_BACKUPDIR should be set."
    exit 1
fi

username=$MONGO_INITDB_ROOT_USERNAME
if [ ! $username ]; then
    read -p "mongodb admin username [admin]: " username
    if [ ! $username ] ; then
        username="admin"
    fi
fi
password=$MONGO_INITDB_ROOT_PASSWORD
if [ ! $MONGO_INITDB_ROOT_PASSWORD ]; then
    read -sp "mongodb admin password: " password
    if [ ! $password ] ; then
        echo ""
        exit 1
    fi
fi
BACKUPDIR=/backup/mongodb/`date +%Y%m%d`
mkdir -p $BACKUPDIR

docker exec `docker ps -q -f ancestor=deploy_mongodb` sh -c "exec mongorestore -v --db IMBase -u $username -p $password $BACKUPDIR/IMBase"

