#!/bin/sh
if [ -f ./.env ] ; then
    export $(cat .env | grep -v ^# | xargs);
fi
if [ ! $GRMS_BACKUPDIR ]; then
    echo "env GRMS_BACKUPDIR should be set."
    exit 1
fi
password=$MYSQL_ROOT_PASSWORD
if [ ! $password ]; then
    read -sp "mysql root password: " password
    if [ ! $password ] ; then
        echo ""
        exit 1
    fi
fi

BACKUPDIR=$GRMS_BACKUPDIR/mysql/all
echo ""
ls $BACKUPDIR
read -p "Select restore file: " target
echo "restore $BACKUPDIR/$target ..."
#docker exec `docker ps -q -f ancestor=mysql:5.7` sh -c "exec mysql -uroot -p$password" < "$BACKUPDIR/$target"
