#!/bin/bash
if [ -f ./.env ] ; then
    export $(cat .env | grep -v ^# | xargs);
fi
if [ ! $GRMS_BACKUPDIR ]; then
    echo "env GRMS_BACKUPDIR should be set."
    exit 1
fi
password=$MYSQL_ROOT_PASSWORD
if [ ! $password ]; then
    read -sp "mysql root password: " password
    if [ ! $password ] ; then
        echo ""
        exit 1
    fi
fi
BACKUPDIR=$GRMS_BACKUPDIR/mysql/each
mkdir -p $BACKUPDIR

dbs=( "IMProjectManagement")

for item in "${dbs[@]}" ; do
    docker exec `docker ps -q -f ancestor=mysql:5.7` sh -c "exec mysqldump -uroot -p$password $item" > $BACKUPDIR/`date +%Y%m%d_%H-%M-%S`-${item}.sql
done
find $BACKUPDIR -name '*.sql' -mtime +10 -delete
